// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MBrace.AWS")>]
[<assembly: AssemblyProductAttribute("MBrace.AWS")>]
[<assembly: AssemblyDescriptionAttribute("AWS PaaS bindings for MBrace")>]
[<assembly: AssemblyMetadataAttribute("Release Signature","Version 0.1.9-alpha, Git Hash 1ff01a, Build Date 08062017 16:29 +01:00")>]
[<assembly: AssemblyVersionAttribute("0.1.9")>]
[<assembly: AssemblyFileVersionAttribute("0.1.9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MBrace.AWS"
    let [<Literal>] AssemblyProduct = "MBrace.AWS"
    let [<Literal>] AssemblyDescription = "AWS PaaS bindings for MBrace"
    let [<Literal>] AssemblyMetadata_Release_Signature = "Version 0.1.9-alpha, Git Hash 1ff01a, Build Date 08062017 16:29 +01:00"
    let [<Literal>] AssemblyVersion = "0.1.9"
    let [<Literal>] AssemblyFileVersion = "0.1.9"
