// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MBrace.AWS")>]
[<assembly: AssemblyProductAttribute("MBrace.AWS")>]
[<assembly: AssemblyDescriptionAttribute("AWS PaaS bindings for MBrace")>]
[<assembly: AssemblyMetadataAttribute("Release Signature","Version 0.1.10-alpha, Git Hash 703331, Build Date 19102017 00:15 +01:00")>]
[<assembly: AssemblyVersionAttribute("0.1.10")>]
[<assembly: AssemblyFileVersionAttribute("0.1.10")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MBrace.AWS"
    let [<Literal>] AssemblyProduct = "MBrace.AWS"
    let [<Literal>] AssemblyDescription = "AWS PaaS bindings for MBrace"
    let [<Literal>] AssemblyMetadata_Release_Signature = "Version 0.1.10-alpha, Git Hash 703331, Build Date 19102017 00:15 +01:00"
    let [<Literal>] AssemblyVersion = "0.1.10"
    let [<Literal>] AssemblyFileVersion = "0.1.10"
