// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MBrace.AWS.StandaloneWorker")>]
[<assembly: AssemblyProductAttribute("MBrace.AWS")>]
[<assembly: AssemblyDescriptionAttribute("AWS PaaS bindings for MBrace")>]
[<assembly: AssemblyMetadataAttribute("Release Signature","Version 0.1.8-alpha, Git Hash bc7362, Build Date 08062017 14:17 +01:00")>]
[<assembly: AssemblyVersionAttribute("0.1.8")>]
[<assembly: AssemblyFileVersionAttribute("0.1.8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MBrace.AWS.StandaloneWorker"
    let [<Literal>] AssemblyProduct = "MBrace.AWS"
    let [<Literal>] AssemblyDescription = "AWS PaaS bindings for MBrace"
    let [<Literal>] AssemblyMetadata_Release_Signature = "Version 0.1.8-alpha, Git Hash bc7362, Build Date 08062017 14:17 +01:00"
    let [<Literal>] AssemblyVersion = "0.1.8"
    let [<Literal>] AssemblyFileVersion = "0.1.8"
